/**
 * @description       : 
 * @author            : esteban@incompany.cr
 * @group             : 
 * @last modified on  : 21-11-2022
 * @last modified by  : esteban@incompany.cr
**/
@isTest
public class WebServiceAccountData {
    @isTest
    public static String getAccountJSON()
    {
        String strJSON = 
        '{'+
            '"AccountMainList": ['+
                '{'+
                    '"codCliente": "1870016",'+
                    '"org": "CAP",'+
                    '"nombreFantasia": "",'+
                    '"direccion": "SABANILLA, MONTES DE OCA, RESIDENCIAL LA MARAVILLA, CASA 25B",'+
                    '"estado": "CONTADO",'+
                    '"razonSocial": "ANTHONY CALDERON GABRIEL",'+
                    '"canton": "1",'+
                    '"cedula": "116340653",'+
                    '"tipocli": "CONSUMIDOR",'+
                    '"reqOc": "NO",'+
                    '"observaciones": "",'+
                    '"sitioWeb": "GABRIEL",'+
                    '"provincia": "1",'+
                    '"porcExoIva": "0",'+
                    '"usuModifica": "AZAMORA",'+
                    '"fyhModifica": "",'+
                    '"horaEntrega": "",'+
                    '"obsEntrega": "",'+
                    '"reqOcEntrega": "",'+
                    '"reqFacEntrega": "",'+
                    '"rutaCobro": "",'+
                    '"limiteCredito": "1000000",'+
                    '"diaTramite": "",'+
                    '"cobradorCxc": "",'+
                    '"fyhIngreso": "",'+
                    '"plazoCxc": "",'+
                    '"nombre1": "GABRIEL",'+
                    '"nombre2": "",'+
                    '"apellido1": "ANTHONY",'+
                    '"apellido2": "CALDERON",'+
                    '"usuIngreso": "AZAMORA",'+
                    '"envEmail": "false",'+
                    '"envSms": "false",'+
                    '"fyhNacimiento": "",'+
                    '"idPuesto": "",'+
                    '"plazoTec": "",'+
                    '"cobradorTec": "",'+
                    '"region": "",'+
                    '"zona": "",'+
                    '"dirComercial": "SABANILLA, MONTES DE OCA, RESIDENCIAL LA MARAVILLA, CASA 25B",'+
                    '"origen": "F",'+
                    '"excepTrans": "false",'+
                    '"indMixto": "false",'+
                    '"fyhVenLetc": "",'+
                    '"vendedor": "",'+
                    '"claCli": "",'+
                    '"codigoPrincipal": "32956",'+
                    '"descripcionCIIU": "Descripcion Marketo Test",'+
                    '"SEM": "test SEM"'+
                '}'+
            ']'+
        '}';

        return strJSON;
    }
}
